name: Node.js CI
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12

    strategy:
      matrix:
        xcode-version: ["13.4.1", "14.2"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Select Xcode ${{ matrix.xcode-version }}
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode-version }}.app
    - name: Remove build directories if they exist
      run: |
        [ -d UICatalog/build ] && rm -rf UICatalog/build
        [ -d UIKitCatalog/build ] && rm -rf UIKitCatalog/build
    - run: npm install

